#
# Packages for Debian in the "stable" channel.
#

trixie:
  version: 13.x
  packages:
  - name: syntalos
    version: 2.1.2
    type: zip
    url: https://github.com/syntalos/syntalos/releases/download/v2.1.2/syntalos_2.1.2+git1509_amd64_debian13.zip
    sha256: b2dfbb55762fbfd422c601ac69c2ab5faab6e7a7f1d7c8ccf74c2801a8deb025

  - name: pomidaq
    version: 0.6.1
    type: zip
    url: https://github.com/bothlab/pomidaq/releases/download/v0.6.1/pomidaq_0.6.1.debian13_amd64.zip
    sha256: 3651ce25436061e556d602d51f47f841b87c0f8588ab399784ad6de7fe0094cf
